### ISSUE TITLE
关于文件导出和出击记录的几点建议

### ISSUE THREAD

**Issue by wafer-li** [poooi/plugin-Akashic-records#10]
#### 文件导出

> 1、**导出文件增加表头**
> 2、希望增加对 `.xls` 和 `.xlsx` 文件的支持，多个 `.csv` 文件切换的确比较麻烦
#### 出击记录

> 对于单场战斗，能否增加一些更为细致的记录，如各个舰娘的伤害，stage 1 & stage 2 的击坠数等等
> （其实就是类似航海日志啦）

**Comment by JenningsWu** [comment]
1. ok
2. 感觉不是很有必要？excel不是可以直接打开csv嘛，也可以直接另存为xlsx？

---

日志之前并没有做如此详细信息记录的计划。毕竟只是poi的一个插件？ ~~记的太详细好累啊_(:з」∠)_~~  
不过也不是不可以做…反正现在为了计算大破已经监听了战斗包了…做成类似战报回顾的那种东西？有具体包括哪些信息的需求么？

**Comment by wafer-li** [comment]
#### 关于 2.

> 其实我的想法是做成一个文件，多个 `sheet` 的形式，这样方便整理和查看记录。不过 `.csv` 不支持多个 `sheet` 才提的这个

#### 关于战斗记录

> _实际上，详细的记录只对于需要测试验证的人有些许的帮助_
> _不过作为一个战报来说，或许具有情怀方面的意义_
> 对的，就是做成一个战报回顾一样的东西
> 实际上类似于航海日志一样记录下来的信息就差不多了
> 具体包括：
> - 索敌、制空状态
> - 侦察机的触接
> - 对空CI的发动者
> - stage 1 & stage 2 的击坠数
> - 各个舰娘对敌舰的伤害
> - 各个舰娘的损害和破损状况（中破、大破等）

**Comment by JenningsWu** [comment]
唔，好的。
感觉提的后两条优先度都不是很高的样子？

---
- [x] 导出csv增加表头

~~\- 单文件多sheet导出。目前感觉用 [js-xlsx](https://github.com/SheetJS/js-xlsx) 比较合适？~~
- [ ] 战斗记录战报回顾

**Comment by hanzhao** [comment]
我认为xlsx支持没有意义
这个格式并不是多平台通用、完全开放的格式

**Comment by JenningsWu** [comment]
有道理！那就不做xlsx啦啦啦

**Comment by Astra-RX** [comment]
制作战报或者战斗记录可以考虑像航海日志一样直接把战斗包抓下来保存，然后用包生即时成报表

**Comment by JenningsWu** [comment]
@PHELiOX 
是这样打算的，存的时候直接存api本体。
现在比较纠结的是这一块要怎么储存和管理…不打算启动的时候载入所有战报，资源占用太多。不是每场战斗都会有战报，比方说早期的记录，以及导入的航海日志的记录就没有战报，所以选择显示战报时要有一个检测是否有详细战报的过程。考虑过每场战斗都单独存在一个文件中，这样方便之后检测和载入，但是这样一来好像文件有点太多了？如果多场战斗合在一个文件里，一是还要单独维护一个列表方便之后检测，二是获得新战报时储存文件的I/O读取会不会有点大…好麻烦。

**Comment by Astra-RX** [comment]
@JenningsWu 
是直接把包存成json或者cson吧？不需要一次性读取所有数据，查看某场战报时在查找就好了。确实每场战斗单独一个文件会数量众多，不过好像也不是不可接受。玩一年下来10k-20k出击数，文件数量也在这个级别，可能HDD读取会慢一些＝。＝
可以考虑使用能够随机存储的压缩格式，按天或者按时间间隔把旧文件压缩到一起，应该可以提高读取效率，asar好像就是这种格式？
目前日志是用什么格式存储的？

**Comment by JenningsWu** [comment]
目前日志以csv格式存储的，新数据直接append在后面。
唔，其实不太清楚10k级别的文件数量会产生什么严重影响么？如果影响不太的话其实也无所谓… 或者就事后按天合并吧
嗯，事后按天合并不错！

**Comment by JenningsWu** [comment]
出击记录见战斗详情插件
