### ISSUE TITLE
刷新游戏页面会导致出击记录丢失

### ISSUE THREAD

**Issue by yukixz** [poooi/plugin-Akashic-records#12]
重现：
1. 关掉航海日志窗口
2. 在设置 > 基本设置 > 浏览器刷新当前页面
3. 再打开航海日志窗口，最近一段时间的记录会丢失。

我这里是固定丢失到 2015/07/09 23:57:13 的某条记录。
远征、建造、开发的记录没有问题。

**Comment by yukixz** [comment]
在打开航海日志窗口的情况下刷新，**似乎**不会丢失记录。

**Comment by JenningsWu** [comment]
@dazzyd 
重现失败…希望帮助求证一些信息。
1. 是否为git最新版？
2. 在记录丢失后，搜索栏中搜索类似“2015/07/12”这种内容，是否能搜到本以为丢失的信息？
3. 重启程序，“丢失的信息”是否会重新显示？
4. 在appData中的poi目录下，进入路径“akashic-records\xxxxxx\attack”，打开20150712（是utf8格式的文本文件，同时也是csv格式），最下方是否有刚才“丢失”的记录？

**Comment by yukixz** [comment]
@JenningsWu
1. 不是 git 版本、是 poi 2.2.0 附带的版本。
2. 搜索可以显示
3. 重启也不会显示
4. akashic-records*\attack 下文本正常。（文件名为 7122015）
系统是 OSX

另外、突然发现航海日志窗口里显示的时间全是 6 月、似乎显示错误？

**Comment by JenningsWu** [comment]
@dazzyd 
信息没有丢失，而是排序出了问题，在显示时排到了后方。这一问题以及显示时间的问题后来均已fix，新版已无这些问题。
不久之后就会发布poi 3.0.0, 其中所带的日志插件已经不会出现这些问题啦。

**Comment by yukixz** [comment]
thx
