### ISSUE TITLE
Bug report link do not work

### ISSUE THREAD

**Issue by wafer-li** [poooi/plugin-Akashic-records#17]
Electron v0.30.1 ia32
Win 10 Pro
commmit:  7b732c4854a6d9036e8cf4e4ae9f5b322130df3e

I clicked the `Bug 汇报` link, but nothing happened.
But I copy the address in the develop tool, and paste it in the browser, it works.
That's really weird

**Comment by JenningsWu** [comment]
Electron forbids `<a href="" />` to open a new window. I forgot this.
Thanks a lot！
