### ISSUE TITLE
窗口crash应对策略引发猫

### ISSUE THREAD

**Issue by JenningsWu** [poooi/plugin-Akashic-records#18]
win8.1 + 岛风go
branch: deal-with-window-crashed
commit: 5a2946bb5f11bd25ed3c2b1a61c0d19c46d36a09
策略: 检测到窗口 crash 后会强制关闭旧窗口，新建窗口。

但发现一个问题，每次这样做之后，都会猫。而且 F5 无效，重启之后也无限黑船。能看到发出了 api 请求，但是不显示收到数据。只有彻底清空缓存之后才能重新进入游戏（并且关掉cmd窗口之后才能删掉全部缓存，不然显示“文件占用中”）

感觉很奇怪啊…可能是什么方面的原因？env？ @magicae

**Comment by JenningsWu** [comment]
另外，之前也出现过几次突然无限猫，只有全部删干净缓存才能进游戏的情况，但不像这次触发原因这么明显。

**Comment by JenningsWu** [comment]
感觉不是个例。是不是和env里的`remote.require '.lib/proxy'`有关，crash 后造成了一些奇怪的影响。
另外，岛风go有个缓存机制好像是未下载完的缓存中途异常终止，也会自动当做已下载完进行更名，作为正确缓存使用。会不会是这个缓存被拿到chromium中了造成上述情况。

**Comment by hanzhao** [comment]
不知道具体原因 不过无限猫通常是因为缓存了未下完或者错误版本的文件

**Comment by JenningsWu** [comment]
新版chromium已不会带来crash问题，不必使用该应对策略。
