### ISSUE TITLE
成功加载过一次之后就都是白屏了

### ISSUE THREAD

**Issue by wafer-li** [poooi/plugin-Akashic-records#2]
版本：electron-v0.28.3-win32-ia32
          poi master分支的最新版本

平台：WIN7 X64 旗舰版

现象：成功加载过一次之后，关掉插件窗口再开就是一片白，完全加载不出内容

**Comment by wafer-li** [comment]
![qq 20150624220947](https://cloud.githubusercontent.com/assets/12459199/8330654/c123b088-1abd-11e5-9248-c2952f3bb122.png)
如图

**Comment by JenningsWu** [comment]
偶然还是常态？
有更多的信息么，比如控制台输出、这种情况出现后developer tool里插件的界面元素情况之类的。
之前也收到过这样的汇报，但因为从来没在debug模式下复现过，目前没找到致使这种情况出现的原因。

**Comment by wafer-li** [comment]
目前版本我重复尝试了近20次，均出现 打开程序=》打开插件=》关闭插件=》白屏  的现象，基本可以认为是常态。
这是最近一次复现现象的console输出
![qq 20150625000652](https://cloud.githubusercontent.com/assets/12459199/8333838/a8f32360-1acf-11e5-9e51-af0e355ece03.png)

JS的调试方法我不是特别了解，请问应如何获取相关信息？

**Comment by JenningsWu** [comment]
非常感谢！最后那条warning很不正常，很可能和此有关。
点进warning右侧的定位链接，在err处设个断点，再次重现，能看到更详细的信息，可以帮助进一步判断。
目前我去外地毕旅了，到27号晚上才回去，有电脑可以用。如果其他人这几天没时间处理这个问题的话，可能到那时才能开始着手处理。
目前猜测这问题可能还与平台有一定关系，mac和win8上出现频率很低。

**Comment by hanzhao** [comment]
给个重现方式 我来debug试试

**Comment by wafer-li** [comment]
@JenningsWu 
我的上一条comment的信息有误，经过测试，我的那个console输出的最后一个warning是由于误点了
“自动适配页面”产生的，与本插件并没有必然联系

@magicae 
重现方式为  启动程序=》打开插件=》关闭插件=》再次打开插件
在我这里就出现了白屏的情况

**Comment by hanzhao** [comment]
Fixed

**Comment by Wafer-Li** [comment]
@magicae  I merge the fix-bug branch, it still doesn' work.

**Comment by hanzhao** [comment]
@Wafer-Li 试试现在的Master?

**Comment by wafer-li** [comment]
@magicae 
其实我在你fixed之后就自行merge了那个fix-bug branch

**Comment by hanzhao** [comment]
@Wafer-Li 结果呢？我这边好像没问题了，你那边呢？

**Comment by wafer-li** [comment]
@magicae 
不好意思没及时反馈
是的，问题已经解决了，感谢

**Comment by hanzhao** [comment]
@Wafer-Li 嗯好！感谢积极测试开发中的插件啦！

**Comment by hanzhao** [comment]
似乎问题还在

**Comment by hanzhao** [comment]
似乎没有问题了
Commit: https://github.com/yudachi/plugin-Akashic-records/commit/6a68879ce4e20c9368f0cfa99a2b8cb8eefd436d

**Comment by hanzhao** [comment]
目前状态 在Electron v0.29.2(Chrome 43)下
Linux / Mac 无法重现
Windows 仍然有报告

**Comment by JenningsWu** [comment]
目前结论是什么？Electron的锅，需要等Electron fix么？

**Comment by hanzhao** [comment]
怀疑是Chrome里的v8的问题 Electron用的是Chrome的v8

**Comment by hanzhao** [comment]
Fix by https://github.com/poooi/poi/commit/43c890a1a59b2c5545aceee513220eb764e50006 .

**Comment by wafer-li** [comment]
换了 Electron v0.30.6 ia32 之后，白屏现象仍有发生，并无任何错误输出信息
平台 WIN 10 X64 PRO
