### ISSUE TITLE
航海日志在3.1.0更新之后打开了之后就不能关闭了

### ISSUE THREAD

**Issue by nanjingsnow** [poooi/plugin-Akashic-records#21]
win10 的系统，在3.0.0的时候还好好的，今天更新之后就发现航海日志打开了就不能关闭了，必须要和整个软件一起关闭才行

**Comment by hanzhao** [comment]
https://github.com/poooi/plugin-Akashic-records/issues/20

查看高级那个选项卡里的问题说明
