### ISSUE TITLE
不能从航海日志里面导入资源数据了

### ISSUE THREAD

**Issue by kevin16323** [poooi/plugin-Akashic-records#22]
更新了3.1.1之后就不能从航海日志导入资源数据了。还有，每次从航海日志导入建造数据的时候舰船种类和船只是反的

**Comment by JenningsWu** [comment]
上传或是发我一份样本？ jenningswu@gmail.com

**Comment by JenningsWu** [comment]
多谢反馈！已fix。
将在3.1.2里解决这一问题，或直接用git版。
