### ISSUE TITLE
Request: Add jschardet to poi's dependency to simplified the Run porcess

### ISSUE THREAD

**Issue by wafer-li** [poooi/plugin-Akashic-records#23]
@magicae  @JenningsWu 
![qq 20150806030928](https://cloud.githubusercontent.com/assets/12459199/9093724/b41e7034-3be8-11e5-941f-39f01fd5109a.png)

Also see here: #9 

---

Edit:
其实能够用 `gulp` 对每个插件进行 `npm` 会更好一点

**Comment by hanzhao** [comment]
已经加在插件的依赖里了 需要到插件目录下npm i一次

**Comment by wafer-li** [comment]
@magicae 
可是每每重新克隆一次就要到目录下npm一次的话，稍显麻烦啊……
在 #9  里面不是有提到可以在gulp里面对各插件运行npm吗？

另外在 #9 中提到的另一个依赖项是可以在poi的dependency中找到的，而这里提到的这个并找不到，从而提出这个issue

**Comment by JenningsWu** [comment]
目前的 RUN guide 中已加入 `git submodule foreach npm i`
