### ISSUE TITLE
繁體中文不能正常顯示

### ISSUE THREAD

**Issue by ShinoharaYuri** [poooi/plugin-Akashic-records#30]
![2](https://cloud.githubusercontent.com/assets/4861352/9847665/859e0fe8-5b15-11e5-8b59-03881106ef7d.PNG)

Poi版本是3.5 插件版本是1.30

**Comment by ruiii** [comment]
繁体中文目前还没有翻译文件 求翻译者

**Comment by ShinoharaYuri** [comment]
欸欸… 原來如此… 那能不能顯示簡體呢…（剛看4.0就是這樣呢

**Comment by ruiii** [comment]
可以显示简体，重启生效。

**Comment by JenningsWu** [comment]
插件的语言跟本体一致的，目前不能本体是繁体中文，插件显示简体呢…英文是在缺省翻译文件的情况下默认显示的语言。
4.0显示简体是因为还没有实装多语言化，所以显示的之前的简体中文。

**Comment by NatLee** [comment]
不知道現在能不能顯示了:+1:
