### ISSUE TITLE
窗口不能关闭

### ISSUE THREAD

**Issue by wafer-li** [poooi/plugin-Akashic-records#34]
Electron v0.33.5 ia32
Win 10 x64 Pro
commit SHA: 543d48a82ec2b49325b68dfda254412f5c6c70f2

点击右上角关闭按钮之后变白屏，再次点击无效。
将窗口最小化之后再还原后界面恢复，
总之就是无法关闭。

**Comment by KochiyaOcean** [comment]
已知 Electron v0.33.4 以上会出现该问题，可能是接口变更所致

**Comment by wafer-li** [comment]
:flushed: 所以是要回退到 v0.33.3 ？

**Comment by KochiyaOcean** [comment]
目前是这样，如果未来更新依赖的话会着手解决

**Comment by wafer-li** [comment]
好的

**Comment by wafer-li** [comment]
[Electron v0.33.6](https://github.com/atom/electron/releases/tag/v0.33.6) seems to fixed it.

**Comment by KochiyaOcean** [comment]
"Fix BrowserWindow.hide not hiding the window."
Oops.
