### ISSUE TITLE
English name of the plugin...

### ISSUE THREAD

**Issue by c933103** [poooi/plugin-Akashic-records#35]
I believe there are many people on the world never heard of "Akashic records" and thus unable to get the reference behind the name of this plugin, and thus when they use the English version of poi they and see the name of this plugin, they might mistakenly relate the plugin's name to something about Akashi or Akashi's Improvement Arsenal, and result in confusion. To avoid this happen, would it be better to translate the name of the plugin into "battle log" or "logbook" in English? This supposingly does not require changing any part of the tool other than the i18n file.

**Comment by JenningsWu** [comment]
I agree with you. Thanks for your advice!
