### ISSUE TITLE
export format

### ISSUE THREAD

**Issue by c933103** [poooi/plugin-Akashic-records#36]
can it use unicode or shift jis as export encoding?

**Comment by JenningsWu** [comment]
The export file's encode is related to the OS. In Windows it uses GB2312, otherwise it uses utf8. So do you mean it should also be related to the language the user uses?

**Comment by c933103** [comment]
yes, that's what I mean.​

2015-10-23 13:21 GMT+08:00 JenningsWu notifications@github.com:
