### ISSUE TITLE
固定资源统计图的坐标尺

### ISSUE THREAD

**Issue by dkwingsmt** [poooi/plugin-Akashic-records#42]
![image](https://cloud.githubusercontent.com/assets/1596656/11765920/20374fd4-a133-11e5-9cb8-4adc23294cdb.png)
好像只对桶等使用右坐标尺的资源

在底栏时间范围不是“全范围”的时候，纵坐标最低值不是0，而是以当前范围内的最低值（减一些）为基准。

建议将最低值固定为0，避免图上这种“看起来是大崩盘但其实只是从1600降到1100”的图表……

以及，建议去掉图上各线段的动画（应该是由插件控制的吧……）

**Comment by JenningsWu** [comment]
1600 -> 1100 已经是大崩盘了吧（
我认为关于最低值，目前的设定是更合理的。固定为 0 不合适，因为这样一来在基础数值很高时，折线图变化幅度会非常低，显示不出来变化情况。整个图表会严重失衡，只有最上方一部分利用到。

线段上的动画是指？
