### ISSUE TITLE
出击记录添加击沉舰、添加解体记录、添加改修消耗船只记录

### ISSUE THREAD

**Issue by yukixz** [poooi/plugin-Akashic-records#45]
- [ ] 出击记录添加击沉舰
- [x] 添加解体记录
- [x] 添加改修消耗船只记录
- [x] 战果是不是没用了？

**Comment by JenningsWu** [comment]
思考 tab 叫什么名字
“退役”？
~~“神隐”？~~

**Comment by yukixz** [comment]
除籍...

**Comment by JenningsWu** [comment]
![s g2l3r 24j b52 rg 1](https://cloud.githubusercontent.com/assets/6861365/12641324/d594dc3a-c563-11e5-990e-316539212f24.png)

**Comment by JenningsWu** [comment]
哦我才注意到是说出击记录里添加击沉字段
这样的话这个字段太空了吧（而且13个tab！tab会多一行！
如果加的话，加到除籍记录里？

**Comment by yukixz** [comment]
可以啊、你开心就好（逃
