### ISSUE TITLE
Use ECharts instead of Chart.js

### ISSUE THREAD

**Issue by hanzhao** [poooi/plugin-Akashic-records#5]
[ECharts](http://echarts.baidu.com/doc/example/line1.html)

It seems ECharts is more powerful and beautiful then Chart.js.
And there are also many themes for ECharts

**Comment by JenningsWu** [comment]
Chart.js局限太大了，是要换掉。之前看了下highcharts，感觉功能上很合适，不知道好不好用。
今晚就回校了，看看EChsrts怎么样。

**Comment by hanzhao** [comment]
嗯

**Comment by JenningsWu** [comment]
It seems that ECharts is more appropriate for our conditions. I will try to use ECharts instead of Chart.js in the next step.

**Comment by hanzhao** [comment]
Closed by https://github.com/yudachi/plugin-Akashic-records/pull/7
