### ISSUE TITLE
定期匯出

### ISSUE THREAD

**Issue by Varitas35** [poooi/plugin-Akashic-records#52]
看能不能在某個資料夾 設定定期匯出功能

**Comment by taroxd** [comment]
把数据存储位置设置到一个与云端同步（Dropbox 之类）的文件夹就可以了。

**Comment by KochiyaOcean** [comment]
Dropbox 之类可以选择自定义文件夹么？如果可以的话直接把 `%appdata%/poi`(Windows) 加进去就行了
