### ISSUE TITLE
使用 lib/proxy 提供的时间戳作为 id

### ISSUE THREAD

**Issue by yukixz** [poooi/plugin-Akashic-records#55]
lib/proxy 的 game.request/response 和相应的 redux action 均已经添加了全局统一的时间戳。
建议使用该时间戳保证与战斗记录插件统一，不存在时再 fallback 回自己生成。

**Comment by JenningsWu** [comment]
`battle.result` 现在带时间戳了是么

**Comment by yukixz** [comment]
没有！

**Comment by yukixz** [comment]
有了！
