### ISSUE TITLE
导入航海日志0.9.10版本的数据部分出错

### ISSUE THREAD

**Issue by xdujiang** [poooi/plugin-Akashic-records#59]
导入远征数据时提示 `不支持的编码或文件格式`
导入出击数据时提示 `cannot read property '0' of null`

其他数据均正常

**Comment by JenningsWu** [comment]
@xdujiang 不介意的话，要导入但是出错的数据发我一份？jenningswu@gmail.com

旅游中，周六回去修（

**Comment by xdujiang** [comment]
@JenningsWu 
已发送
大佬出去玩还不忘回issue啊(｀･ω･)

**Comment by JenningsWu** [comment]
已修
