### ISSUE TITLE
几点建议

### ISSUE THREAD

**Issue by jayjayzju** [poooi/plugin-Akashic-records#6]
1、比如我不想看而舰队的旗舰和MVP，去掉勾选后，重开poi，不会保存这个设置。其它几个统计的设置也一样
2、资源统计表默认按天数显示
3、资源统计 - 按小时显示，第二页，此时切回按天显示，不足一页时显示为空，需要再点一下第一页
4、资源统计走势图，资源和资材的上限不一样，可以分左右两个维度显示
5、远征日志可以统计单个远征的物品收益率，比如远征2的捞桶收益

**Comment by JenningsWu** [comment]
1、2将在下个版本实现。关于2，初始默认按照天数显示，保存用户更改的设置。
3也将在下个版本fix掉
关于4，目前显示走势图所用的chart.js要支持复杂的显示比较麻烦。在更换掉之后，会重点考虑资源和资材的纵坐标轴单位问题。
5是个很好的建议，你觉得远征的统计放到哪里比较好？目前有个想法是在远征日志界面加一块数据统计区域，实时计算当前远征的某些统计数据，而计算范围是根据“搜索”那里检索的数据确定的。这样在以某远征名为关键字进行检索时，数据统计区就可以显示特定远征单个远征物品收益率。

感谢建议！

**Comment by malichan** [comment]
关于5我觉得可以放在数据汇报里……

**Comment by JenningsWu** [comment]
1~4已完成
5待处理
