### ISSUE TITLE
win10显示不正确

### ISSUE THREAD

**Issue by DDEle** [poooi/plugin-Akashic-records#61]
资源选项卡（姑且这么称呼）右上角图标显示不正确。上面一排资源种类点击区域与字样所在地错位。下面的放大缩小条无法拉动（我也不知道什么时候开始这样的，我记得之前是可以拉动放大缩小的。

**Comment by KochiyaOcean** [comment]
插件和本体版本？
另外希望至少有截图……

**Comment by DDEle** [comment]
大佬居然秒回！！鸡冻
插件6.0.5 本体 7.8.0
不好意思 作为新生的程序猿还不会熟练使用git 一下子没看到上传图片的地方就懒了一下
然而 上传图片几次都不行 无奈先去度盘转一下（如下（因此浪费了一点事回复大佬

https://pan.baidu.com/s/1nuMvlET

**Comment by KochiyaOcean** [comment]
图片如果网络没问题的话复制以后直接粘贴就行了

**Comment by KochiyaOcean** [comment]
有设置过本体的缩放等级么

**Comment by KochiyaOcean** [comment]
试着更新到 7.9.0-beta.1 看看有没有相同问题？

**Comment by DDEle** [comment]
（谢谢上传图片的方法，然而总是提示出错 sth went really wrong, and we can't process that file. 感觉可能是网络问题
anyway， 确实是缩放等级的问题 调到100就没有问题了。然而还是希望有空的话可以对本体缩放等级做一下优化（虽然猜测可能非常麻烦。不过还是谢谢，下次需要看的时候零时把缩放等级调到100就好了

**Comment by KochiyaOcean** [comment]
如果是缩放设置的问题的话 7.9.0 大概是修复了，可以更新测试版看看

**Comment by DDEle** [comment]
好的，我明天有空试一下给你反馈。（暂时我还是在东八区的lowb

**Comment by tojo17** [comment]
缩放问题 7.9.0 b1 已经修复了，感谢开发者。
