### ISSUE TITLE
希望增加删除指定天数前的记录的功能

### ISSUE THREAD

**Issue by HaneRo** [poooi/plugin-Akashic-records#66]
希望增加记录最长保留时间的功能，并支持手动删除部分记录

**Comment by JenningsWu** [comment]
手动删除最方便的方式是导出之后清空数据，然后删除部分记录之后再导入。

如果是要按时间删除战斗记录的话，可以直接到 `%APPDATA/poi/akashic-records/<user-id>/attack`里直接删。战斗记录的话是按日期存储的。

直接从插件里删的话，过段时间我加一下好了。
