### ISSUE TITLE
请问正则表达式要怎么写？

### ISSUE THREAD

**Issue by LBCHN** [poooi/plugin-Akashic-records#81]
如题，目前写诸如[0-9]、\w等常见匹配字符都匹配不到任何内容。
![poi_wZ37EgTIeb](https://user-images.githubusercontent.com/35479348/89750610-4c4f4300-daff-11ea-995c-5997abf86900.png)
除了在海域中写n莫名其妙地匹配到了48-2。
![Poi_Regexp](https://user-images.githubusercontent.com/35479348/89750710-b2d46100-daff-11ea-9587-1fb487764aae.png)
请问**航海日志中的正则表达式**要怎么写？谢谢。

**Comment by KochiyaOcean** [comment]
两头加上 `/`
![image](https://user-images.githubusercontent.com/8194131/89754953-a90b2780-db18-11ea-992a-827b9aa64375.png)
