### ISSUE TITLE
Exports gibberish with Japanese POI UI language (Changing encoding doesn't help)

### ISSUE THREAD

**Issue by Mattz-P** [poooi/plugin-Akashic-records#83]
I'm not expecting responses but essentially My OS is in English and POI UI is in japanese. If I read the file through excel, which is in english, question mark appears. Then, I thought of importing the data and encode it using Japanese JIS, which didn't solve the issue.
![image](https://user-images.githubusercontent.com/33806410/116247754-201b4580-a7a6-11eb-92a9-3836e98b48f9.png)

**Comment by KagamiChan** [comment]
@Mattz-P please use utf8 or utf-8

**Comment by Mattz-P** [comment]
Thank you, I tried searching it up in Chinese encoding section but forgot to look for "Unicode (UTC-8)" directly
