### ISSUE TITLE
打开就是黑屏，啥都没有

### ISSUE THREAD

**Issue by wafer-li** [poooi/plugin-Akashic-records#9]
version: commit SHA: 8b79f48fcab06ca758310f6eca92193c6eb25e0a

![qq 20150709065107](https://cloud.githubusercontent.com/assets/12459199/8583235/fc350d12-2606-11e5-846e-c690f8788ad1.png)

一打开插件就是黑的一片。
console的输出在打开前后没有变化

**Comment by hanzhao** [comment]
console里输入
akashicRecords.openDevTools({detach: true})
把消息发上来

**Comment by wafer-li** [comment]
@magicae 
![qq 20150709083903](https://cloud.githubusercontent.com/assets/12459199/8584848/0bd9a2b4-2616-11e5-940a-dc12bf462683.png)

**Comment by wafer-li** [comment]
@magicae 
![qq 20150709084346](https://cloud.githubusercontent.com/assets/12459199/8584918/ba723a20-2616-11e5-93cc-9f63e95da279.png)

**Comment by hanzhao** [comment]
@JenningsWu 有undefined被Render了

**Comment by JenningsWu** [comment]
咦？之前没看见。现在的git版仍然有这种情况么？
如果有的话，是
1、进入游戏前已经打开，黑屏
2、进入游戏后打开，黑屏
3、玩了一段时间后打开，黑屏
三种情况中的那一种？还是不论什么时候打开都会黑屏？

**Comment by wafer-li** [comment]
@JenningsWu 
重新克隆了一遍poi，嗯……问题又消失了。
估计是我这边出了什么差错。

**Comment by wafer-li** [comment]
@JenningsWu 
情况重新出现，为了验证，pull 到了最新的poi版本。
具体情况属于第三种，就是无论什么时候打开都是黑屏
![qq 20150711022921](https://cloud.githubusercontent.com/assets/12459199/8624750/2c8865ee-2775-11e5-8a0d-d705d01d6464.png)

**Comment by KochiyaOcean** [comment]
呃这是没更新 submodule？

**Comment by JenningsWu** [comment]
需要跑去日志插件目录下跑一遍
`npm install`
新插件加入了对iconv-lite的依赖

**Comment by wafer-li** [comment]
@JenningsWu  @KochiyaOcean 
Solved

**Comment by wafer-li** [comment]
@JenningsWu 
以后再次出现这种状况的话在 poi 的 root 目录跑一遍 npm 行不行？

**Comment by JenningsWu** [comment]
@Wafer-Li 
不确定，对npm包管理不熟…不过感觉光在root目录下跑是不行的。
@magicae 要不把iconv-lite加到poi的dependences里吧！

**Comment by hanzhao** [comment]
我在gulp里可以自动各个路径分别npm install

**Comment by hanzhao** [comment]
另外为了标准化我提倡每个插件一个package.json！
